apiVersion: v1
kind: Service
metadata:
  name: kube-vip-controller
  namespace: kube-system
spec:
  ports:
    - port: 8080
      name: http
      protocol: TCP
  selector:
    app: kube-vip-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-vip-controller
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-vip-controller
  template:
    metadata:
      labels:
        app: kube-vip-controller
    spec:
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      serviceAccountName: kube-vip-controller
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: kube-vip-controller
              topologyKey: kubernetes.io/hostname
      containers:
        - name: webhook
          image: busybox:latest
          command:
            - /bin/sh
            - -c
            - "tail -f /dev/null"
          
          # Use kube-vip-controller when load image with kind cluster
          #image: kube-vip-controller
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
