apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "kube-vip-controller.fullname" . }}
data:
    ENDPOINT: "0.0.0.0:{{ .Values.service.port }}"
    SEND_REQUEST_PORT: "{{ .Values.kubeVip.send_request_port }}"
    SEND_REQUEST_PATH: "{{ .Values.kubeVip.send_request_path }}"
    SEND_REQUEST_HTTPS: "{{ .Values.kubeVip.send_request_https }}"
    KUBE_VIP_LEASE_NAME: "{{ .Values.kubeVip.kube_vip_lease_name }}"
    DAEMONSET_NAME: "{{ .Values.kubeVip.daemonset_name }}"

